chore: cleanup

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -54,12 +54,12 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-#      - name: Ensure branch is main
-#        if: github.ref != 'refs/heads/main'
-#        run: |
-#          text="Publish a new version can only be done from the main branch."
-#          echo "::error title=Wrong Branch::$text"
-#          exit 1
+      - name: Ensure branch is main
+        if: github.ref != 'refs/heads/main'
+        run: |
+          text="Publish a new version can only be done from the main branch."
+          echo "::error title=Wrong Branch::$text"
+          exit 1
 
       - name: Read current version
         run: |
